// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package todo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Todo_TodoStatus int32

const (
	Todo_TODO Todo_TodoStatus = 0
	Todo_DONE Todo_TodoStatus = 1
)

var Todo_TodoStatus_name = map[int32]string{
	0: "TODO",
	1: "DONE",
}

var Todo_TodoStatus_value = map[string]int32{
	"TODO": 0,
	"DONE": 1,
}

func (x Todo_TodoStatus) String() string {
	return proto.EnumName(Todo_TodoStatus_name, int32(x))
}

func (Todo_TodoStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0, 0}
}

type Todo struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("todo.Todo_TodoStatus", Todo_TodoStatus_name, Todo_TodoStatus_value)
	proto.RegisterType((*Todo)(nil), "todo.Todo")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc9, 0x4f, 0xc9,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xa2, 0xb8, 0x58, 0x42, 0xf2,
	0x53, 0xf2, 0x85, 0x14, 0xb8, 0xb8, 0x53, 0x52, 0x8b, 0x93, 0x8b, 0x32, 0x0b, 0x4a, 0x32, 0xf3,
	0xf3, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x85, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53,
	0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x94, 0x14, 0xb8, 0xb8, 0x40, 0x3a,
	0x83, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x85, 0x38, 0xb8, 0x58, 0x42, 0xfc, 0x5d, 0xfc, 0x05, 0x18,
	0x40, 0x2c, 0x17, 0x7f, 0x3f, 0x57, 0x01, 0xc6, 0x24, 0x36, 0xb0, 0x45, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xd3, 0x83, 0x98, 0xc8, 0x76, 0x00, 0x00, 0x00,
}
